seed: 42

data:
  decouple_kv: true
  length: 2048
  n_pairs: 8
  num_values: 64
  train_size: 8000
  val_size: 800
  vocab_extra: 96

model:
  emb_dim: 64
  hid_dim: 128
  mem_dim: 1024

memory:
  n_slots: 2048
  k_top: 32

train:
  batch_size: 16
  lr: 0.003
  wd: 0.01
  epochs: 12
  lr_after_warm_factor: 0.5
  num_workers: 0

emma:
  deq_max_iter: 8
  oracle_write: false
  warm_start_epochs: 2
  oracle_mix_ramp_epochs: 6
  oracle_mix_min: 0.3
  mem_into_deq: true
  mem_scale: 0.5
  mem_scale_min: 0.0
  logit_scale_max: 5.0
  nce_gate_write_cos: 0.15

loss:
  lambda_pred_ce: 0.6
  lambda_write_cos: 1.0
  lambda_write_nce: 0.2   # gated on when write_cos >= nce_gate_write_cos
