seed: 42

data:
  decouple_kv: true
  length: 512
  n_pairs: 4
  num_values: 64
  train_size: 4000
  val_size: 400
  vocab_extra: 96

model:
  emb_dim: 64
  hid_dim: 96
  mem_dim: 512

memory:
  n_slots: 512
  k_top: 24

train:
  batch_size: 32
  lr: 0.002
  wd: 0.01
  epochs: 6
  lr_after_warm_factor: 0.5

emma:
  deq_max_iter: 8
  oracle_write: false
  warm_start_epochs: 2
  oracle_mix_ramp_epochs: 4
  oracle_mix_min: 0.3
  mem_into_deq: true
  mem_scale: 0.3    # start gentle; scheduler will ramp during training
  mem_scale_min: 0.0
  logit_scale_max: 5.0
  nce_gate_write_cos: 0.15

loss:
  lambda_pred_ce: 0.6
  lambda_write_cos: 1.5
  lambda_write_nce: 0.0  # keep off on CPU mid-run

